CREATE INDEX CONCURRENTLY "_dek_storage_kek_label_idx" ON "_dek_storage"("kek_label");
CREATE INDEX CONCURRENTLY "person__first_name_idx" ON "person"(normalize("first_name", NFKC));
CREATE INDEX CONCURRENTLY "person__last_name_idx" ON "person"(normalize("last_name", NFKC));
CREATE INDEX CONCURRENTLY "person__comment_cgsearch" ON "person"("extensions".contentgrid_prefix_search_normalize("comment") text_pattern_ops);
CREATE INDEX CONCURRENTLY "person__comment_idx_english" ON "person" USING GIN(to_tsvector('English', "extensions".contentgrid_prefix_search_normalize("comment")));
CREATE INDEX CONCURRENTLY "shipment__address_city_idx" ON "shipment"(normalize("address_city", NFKC));
CREATE INDEX CONCURRENTLY "shipment__address_country_idx" ON "shipment"(normalize("address_country", NFKC));
CREATE INDEX CONCURRENTLY "shipment__address_residence_street_idx" ON "shipment"(normalize("address_residence_street", NFKC));
CREATE INDEX CONCURRENTLY "shipment__address_residence_number_idx" ON "shipment"(normalize("address_residence_number", NFKC));
CREATE UNIQUE INDEX CONCURRENTLY "invoice__number_idx" ON "invoice"(normalize("number", NFKC));
CREATE INDEX CONCURRENTLY "invoice__amount_idx" ON "invoice"("amount");
CREATE INDEX CONCURRENTLY "shipment__invoice_idx" ON "shipment"("invoice");
CREATE INDEX CONCURRENTLY "invoice__customer_idx" ON "invoice"("customer");
