spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
contentgrid:
  appserver:
    application-model: classpath:application-model.json
    content-store:
      type: ephemeral
    query-engine:
      bootstrap-tables: true
  thunx:
    abac:
      source: none
server:
  port: ${PORT:8080}
  max-http-request-header-size: 10MB
