plugins {
    id 'java-platform'
    id 'maven-publish'
}

javaPlatform {
    allowDependencies()
}

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:4.0.7')
    api platform('com.contentgrid.thunx:thunx-bom:0.16.1')
    api platform('software.amazon.awssdk:bom:2.51.2')

    constraints {
        api 'org.hamcrest:hamcrest:3.0'

        api 'com.contentgrid.hateoas:contentgrid-pagination-api:1.0.1'
        api 'com.contentgrid.hateoas:contentgrid-hateoas-spring:1.0.1'
        api 'com.contentgrid.hateoas:contentgrid-hateoas-uritemplate:1.0.1'

        api 'com.fasterxml.uuid:java-uuid-generator:5.2.0'

        api 'com.adobe.testing:s3mock-testcontainers:5.1.0'

        api 'com.networknt:json-schema-validator:1.5.9'
        api 'uk.co.datumedge:hamcrest-json:0.3'

        api 'commons-io:commons-io:2.22.0'
    }
}
