spring:
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:contentgrid}
    username: ${DB_USERNAME:contentgrid}
    password: ${DB_PASSWORD:contentgrid}
  mvc.problemdetails.enabled: true
server:
  port: ${PORT:8080}
  max-http-request-header-size: 10MB  # needed for abac-context
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: '8081'
