contentgrid:
  thunx:
    abac:
      source: none
  security:
    csrf.disabled: true
    unauthenticated.allow: true
  appserver:
    query-engine.bootstrap-tables: true
    content-store.type: ephemeral
    content:
      encryption:
        bootstrap-tables: true
  system:
    application-id: dece6818-fab2-11f0-aa04-17747aaadf5e
    deployment-id: e5708fca-fab2-11f0-ab48-1b1797482fc9
    policyPackage: xfb0e9318f3894300a64edba3532e6ac0
  events:
    rabbitmq.enabled: false
    webhook-config-url: http://localhost:${management.server.port}/actuator/webhooks

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# spring:
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest

# When unauthenticated, you get HTTP 403 instead of 401 if you don't have the following

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: 'https://auth.contentgrid.com/realms/contentgrid-dev'