spring:
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: ${PORT:8080}
  tomcat:
    max-part-count: 200
management:
  server:
    port: 8081
  health:
    rabbit:
      enabled: true
