plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    implementation project(':contentgrid-appserver-infrastructure-api')
    implementation project(':contentgrid-appserver-infrastructure-impl-fs')
    implementation 'io.minio:minio'

    testImplementation 'org.assertj:assertj-core'
    testImplementation testFixtures(project(':contentgrid-appserver-infrastructure-api'))
    testImplementation testFixtures(project(':contentgrid-appserver-contentstore-impl-utils'))
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "com.adobe.testing:s3mock-testcontainers"
}

