contentgrid:
  thunx:
    abac:
      source: opa
  security:
    csrf.disabled: true
    unauthenticated.allow: true
  appserver:
    query-engine:
      bootstrap-tables: create
    content-store.type: ephemeral
    blueprint-artifact:
      location: classpath:.
  system:
    application-id: dece6818-fab2-11f0-aa04-17747aaadf5e
    deployment-id: e5708fca-fab2-11f0-ab48-1b1797482fc9
  events:
    rabbitmq.enabled: false
    webhook-config-url: http://localhost:${management.server.port}/actuator/webhooks

opa:
  service:
    url: http://localhost:8181
  query: data.contentgrid.appserver.allow == true

spring:
  datasource:
    url: jdbc:tc:postgresql:15:///
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include:
            - readinessState
            - opa

# spring:
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest

# When unauthenticated, you get HTTP 403 instead of 401 if you don't have the following

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: 'https://auth.contentgrid.com/realms/contentgrid-dev'
