plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    api project(':contentgrid-appserver-contentstore-api')
    implementation project(':contentgrid-appserver-application-model')
    implementation project(':contentgrid-appserver-query-engine-api')
    implementation 'org.jooq:jooq'
    implementation 'org.springframework:spring-tx'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'io.micrometer:micrometer-core'
    implementation 'org.slf4j:slf4j-api'
    runtimeOnly 'org.postgresql:postgresql'

    annotationProcessor "org.jooq:jooq-checker:3.20.11"
    testAnnotationProcessor "org.jooq:jooq-checker:3.20.11"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jooq'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation testFixtures(project(':contentgrid-appserver-application-model'))
    testImplementation testFixtures(project(':contentgrid-appserver-contentstore-impl-utils'))
}

tasks.withType(JavaCompile) {
    options.fork = true
    options.compilerArgs += [
            '-processor', 'org.jooq.checker.PlainSQLChecker' +
            ',lombok.launch.AnnotationProcessorHider$AnnotationProcessor'
    ]
    options.forkOptions.jvmArgs += [
            "--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
            "--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
            "--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED"
    ]
}
