plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    api project(':contentgrid-appserver-application-model')
    api project(':contentgrid-appserver-domain')

    api 'org.springframework.boot:spring-boot-starter'

    api 'org.springframework.boot:spring-boot-starter-amqp'
    api 'org.springframework.boot:spring-boot-jackson2'
    implementation project(':contentgrid-appserver-rest')

    testImplementation project(':contentgrid-appserver-spring-boot-starter')
    testImplementation project(':contentgrid-appserver-app')
    testImplementation project(':contentgrid-appserver-rest')
    testImplementation testFixtures(project(':contentgrid-appserver-application-model'))
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
