plugins {
    id 'java-library'
    id 'io.freefair.lombok'
    id 'java-test-fixtures'
}

dependencies {

    testFixturesImplementation project(':contentgrid-appserver-spring-boot-starter')
    testFixturesImplementation 'org.springframework.boot:spring-boot-starter-test'
    testFixturesImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testFixturesImplementation 'org.testcontainers:testcontainers-postgresql'
    testFixturesImplementation 'org.testcontainers:testcontainers-rabbitmq'
    testFixturesRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testFixturesRuntimeOnly 'org.testcontainers:testcontainers-postgresql'


    testImplementation project(':contentgrid-appserver-domain')
    // should not be used for most integration tests, but relevant for encryption compatibility
    testImplementation project(':contentgrid-appserver-contentstore-impl-encryption')
    testImplementation testFixtures(project(':contentgrid-appserver-rest'))
    testImplementation testFixtures(project(':contentgrid-appserver-contentstore-impl-utils'))

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.hateoas:spring-hateoas'
    testImplementation 'org.springframework.security:spring-security-oauth2-jose'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework:spring-tx'
    testImplementation 'org.springframework:spring-webflux'
    testImplementation 'org.hamcrest:hamcrest'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'com.adobe.testing:s3mock-testcontainers'
}
