plugins {
    id 'java-library'
    id 'java-test-fixtures'
    id 'io.freefair.lombok'
    id 'org.springframework.boot'
}

dependencies {

    implementation project(':contentgrid-appserver-spring-boot-starter')
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.hamcrest:hamcrest'
}

bootRun {
    systemProperty('spring.profiles.active', 'bootRun')
    classpath += sourceSets.testFixtures.output
    classpath += configurations.testFixturesRuntimeClasspath
}

bootBuildImage {
    def dockerImageRepo = "ghcr.io/xenit-eu/contentgrid-appserver"
    imageName = "${dockerImageRepo}:${project.version}"
    tags = "${project.version}".endsWith('SNAPSHOT') ? [ "${dockerImageRepo}:SNAPSHOT" ] : null

    if (!ci.isCi()) {
        tags.add("${dockerImageRepo}:local")
    }

    docker {
        publishRegistry {
            url = project.findProperty('DOCKER_PUBLISH_REGISTRY_URL')
            username = project.findProperty('DOCKER_PUBLISH_REGISTRY_USERNAME')
            password = project.findProperty('DOCKER_PUBLISH_REGISTRY_PASSWORD')
        }
    }
}
