plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

configurations {
    compileOnly {
        extendsFrom(annotationProcessor)
    }
}

dependencies {
    implementation project(':contentgrid-appserver-rest')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.hateoas:spring-hateoas'
    implementation 'com.contentgrid.thunx:thunx-spring-security'
    implementation 'com.contentgrid.hateoas:contentgrid-hateoas-spring'

    testImplementation project(':contentgrid-appserver-app')
    testImplementation testFixtures(project(':contentgrid-appserver-rest'))
    testImplementation testFixtures(project(':contentgrid-appserver-application-model'))

    testImplementation 'com.contentgrid.thunx:thunx-encoding-json'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}

tasks.named('test') {
    useJUnitPlatform()
}
