plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'com.contentgrid.thunx:thunx-autoconfigure'

    compileOnly project(':contentgrid-appserver-application-model')
    compileOnly project(':contentgrid-appserver-application-model-json')
    compileOnly project(':contentgrid-appserver-actuators')
    compileOnly project(':contentgrid-appserver-contentstore-api')
    compileOnly project(':contentgrid-appserver-contentstore-impl-encryption')
    compileOnly project(':contentgrid-appserver-contentstore-impl-fs')
    compileOnly project(':contentgrid-appserver-contentstore-impl-s3')
    compileOnly project(':contentgrid-appserver-domain')
    compileOnly project(':contentgrid-appserver-events')
    compileOnly project(':contentgrid-appserver-infrastructure-api')
    compileOnly project(':contentgrid-appserver-infrastructure-impl-fs')
    compileOnly project(':contentgrid-appserver-query-engine-api')
    compileOnly project(':contentgrid-appserver-query-engine-impl-jooq')
    compileOnly project(':contentgrid-appserver-rest')
    compileOnly project(':contentgrid-appserver-webjars')

    compileOnly 'com.contentgrid.thunx:thunx-spring-security'

    compileOnly 'io.minio:minio'
    compileOnly 'com.squareup.okhttp3:okhttp'
    compileOnly 'org.flywaydb:flyway-core'
    compileOnly 'org.flywaydb:flyway-database-postgresql'
    compileOnly 'org.jooq:jooq'
    compileOnly 'org.springframework:spring-tx'
    compileOnly 'org.springframework.hateoas:spring-hateoas'
    compileOnly 'org.springframework.security:spring-security-web'
    compileOnly 'org.springframework.security:spring-security-oauth2-jose'

    // dependencies for AnonymousHttpConfigurer
    compileOnly 'org.springframework.security:spring-security-config'
    compileOnly 'org.springframework.security:spring-security-web'
    compileOnly 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    testImplementation 'org.springframework.boot:spring-boot-starter-jooq'
    testImplementation 'org.springframework.boot:spring-boot-actuator-autoconfigure'
    testImplementation 'org.springframework.security:spring-security-test'

    testImplementation project(':contentgrid-appserver-actuators')
    testImplementation project(':contentgrid-appserver-application-model')
    testImplementation project(':contentgrid-appserver-application-model-json')
    testImplementation project(':contentgrid-appserver-contentstore-api')
    testImplementation project(':contentgrid-appserver-contentstore-impl-encryption')
    testImplementation project(':contentgrid-appserver-contentstore-impl-fs')
    testImplementation project(':contentgrid-appserver-contentstore-impl-s3')
    testImplementation project(':contentgrid-appserver-domain')
    testImplementation project(':contentgrid-appserver-events')
    testImplementation project(':contentgrid-appserver-infrastructure-api')
    testImplementation project(':contentgrid-appserver-infrastructure-impl-fs')
    testImplementation project(':contentgrid-appserver-query-engine-api')
    testImplementation project(':contentgrid-appserver-query-engine-impl-jooq')
    testImplementation project(':contentgrid-appserver-rest')
    testImplementation testFixtures(project(':contentgrid-appserver-contentstore-impl-encryption'))
    testImplementation testFixtures(project(':contentgrid-appserver-infrastructure-impl-fs'))

    testImplementation 'com.contentgrid.thunx:thunx-spring-security'
    testRuntimeOnly 'org.springframework:spring-webflux'

    testImplementation 'io.minio:minio'
    testImplementation 'org.springframework.hateoas:spring-hateoas'
}

test {
    useJUnitPlatform()
}
