plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {

    implementation 'jakarta.servlet:jakarta.servlet-api'
    implementation 'org.springframework:spring-webmvc'
    implementation 'org.webjars:swagger-ui:5.32.5'
    implementation 'org.webjars:hal-explorer:2.3.0'
    implementation 'org.webjars:webjars-locator-core'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    testRuntimeOnly 'jakarta.servlet:jakarta.servlet-api'
}
