plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    implementation project(':contentgrid-appserver-domain-spi')

    testImplementation 'org.assertj:assertj-core'
    testImplementation testFixtures(project(':contentgrid-appserver-domain-spi'))
}

