plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    implementation project(':contentgrid-appserver-application-model')
    implementation 'tools.jackson.core:jackson-databind'

    testImplementation 'org.assertj:assertj-core'
    testImplementation 'tools.jackson.dataformat:jackson-dataformat-yaml'
    testImplementation testFixtures(project(':contentgrid-appserver-application-model'))
    testImplementation project(':contentgrid-appserver-application-model-json')
}
