plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    implementation project(':contentgrid-appserver-domain-spi')
    implementation project(':contentgrid-appserver-blueprintartifact-impl-fs')
    implementation project(':contentgrid-appserver-blueprintartifact-impl-utils')
    implementation 'software.amazon.awssdk:s3'

    testImplementation 'org.assertj:assertj-core'
    testImplementation testFixtures(project(':contentgrid-appserver-blueprintartifact-impl-utils'))
    testImplementation testFixtures(project(':contentgrid-appserver-contentstore-impl-utils'))
    testImplementation testFixtures(project(':contentgrid-appserver-autoconfigure'))
    testImplementation "org.testcontainers:testcontainers-junit-jupiter"
    testImplementation "com.adobe.testing:s3mock-testcontainers"
}

