name: build
on:
  push:
  pull_request:

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
          cache: gradle
      - name: Build and Test
        run: ./gradlew build