plugins {
    id 'java-library'
    id 'maven-publish'
    id 'io.freefair.lombok'
}

dependencies {
    api project(':contentgrid-appserver-contentstore-api')
    implementation project(':contentgrid-appserver-contentstore-impl-utils')
    implementation 'software.amazon.awssdk:s3'

    testImplementation testFixtures(project(':contentgrid-appserver-contentstore-impl-utils'))
    testImplementation testFixtures(project(':contentgrid-appserver-autoconfigure'))
    testImplementation 'org.awaitility:awaitility'
    testImplementation "org.springframework.boot:spring-boot-testcontainers"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter"

    testImplementation "com.adobe.testing:s3mock-testcontainers"
}

